name: newsly
description: A professional news application built with Flutter.
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0
  flutter_spinkit: ^5.2.1
  lottie: ^3.3.1
  async: ^2.13.0
  rxdart: ^0.28.0

flutter:
  assets:
    - assets/images/newsly.png
    - assets/images/newsly1.jpg

